apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.releaseName }}-cert
  namespace: istio-ingress
spec:
  dnsNames:
    - {{ .Values.dnsName }}
  secretName: {{ .Values.releaseName }}-cert-tls
  issuerRef:
    name: jack-newbury-selfsigned
