apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.releaseName }}-https-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.releaseName }}-cert-tls
      hosts:
        - {{ .Values.dnsName }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.releaseName }}-https
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.dnsName }}
  gateways:
    - {{ .Values.releaseName }}-https-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Values.releaseName }}
            port:
              number: 80
