apiVersion: v1
kind: Service
metadata:
  name: { { .values.releaseName } }
  namespace: { { .values.namespace } }
spec:
  ports:
    - port: 80
      targetPort: { { .values.containerPort } }
  selector:
    app: { { .values.releaseName } }
